version: 0.2

phases:
  install:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  pre_build:
    commands:
      - echo Pre-build phase...
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      # Navigate to the build directory and create a zip file without the root directory
      - cd build
      # - zip -r -q ../build.zip .
artifacts:
  # Specify the contents of the completed build as the artifact
  files:
    # - build.zip
    -'**/*'
    base-directory: build
