version: 0.2

phases:
  install:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  pre_build:
    commands:
      - echo Pre-build phase...
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      # No need to navigate anywhere, just zip the contents of the build directory
      - zip -r build.zip build/*
      # Make sure the build.zip is in the root directory
      - ls -alh

artifacts:
  # Specify the zip file at the root of the workspace as the artifact
  files:
    - build.zip
